# Generated by Django 2.2.5 on 2020-03-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_addquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddQuestions',
            new_name='AddQuestionsModel',
        ),
    ]
