# Generated by Django 2.2.5 on 2020-03-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0004_auto_20200310_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddQuestionsModel',
        ),
    ]
