# Generated by Django 2.2.5 on 2020-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0009_auto_20200405_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestionsmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
