# Generated by Django 2.2.5 on 2020-04-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0010_auto_20200406_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestionsmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.AdduserModel'),
        ),
    ]
